"""Normative identifiers for the V10.1 C-AMC-sem certificate route."""

PROOF_ROUTE = "C_AMC_SEM_BASE_OR_POLICY_CONSTRAINED_SINGLE_SWITCH_CERTIFICATE_V10_1"
REQUEST_SCHEMA = "proof_request_v10_1"
SCOPE = "P0_ZERO_CONTROLLER_OVERHEAD"
PRIMARY_CLAIM = "DEPLOYED_HI_SAFETY_P0"
FRAMEWORK_REVISION = "V10.16_ADAPTIVE_PHASE_BLOCK_PCSSC"

RESULT_PROVED = "DEPLOYED_TREE_PROVED_P0_V10_1"
RESULT_UNRESOLVED = "UNRESOLVED"
RESULT_INVALID = "PROOF_BUNDLE_INVALID"
RESULT_CONCRETE_COUNTEREXAMPLE = "CONCRETE_HI_COUNTEREXAMPLE_VERIFIED"

TARGET_PROVED_BASE = "TARGET_PROVED_BY_BASE_C_AMC_SEM"
TARGET_PROVED_PCSSC = "TARGET_PROVED_BY_PCSSC"
TARGET_PROVED_PCSSC_CASE_CONSISTENT = "TARGET_PROVED_BY_PCSSC_CASE_CONSISTENT"
TARGET_PROVED_PCSSC_CASE_CONDITIONED_CARRY = "TARGET_PROVED_BY_PCSSC_CASE_CONDITIONED_CARRY_V10_13"
TARGET_PROVED_PCSSC_REFINED_CASES_V10_16 = "TARGET_PROVED_BY_PCSSC_REFINED_CASES_V10_16"

CANONICAL_PHASES = (
    "SETTLE_SERVICE_AND_REMOVAL",
    "IDLE_RECOVERY",
    "DEADLINE_OBSERVE",
    "ARRIVAL_BATCH_FREEZE",
    "MODE_SWITCH",
    "CONTROLLER",
    "FINAL_DISPATCH",
    "TIME_ADVANCE_AND_SERVICE",
)

KERNEL_STATE_FIELDS = ("t", "p", "m", "B", "eta", "J", "F", "M", "chi")

# Retired terminal obligations are intentionally absent from the V10.1 PASS DAG.
STATIC_OBLIGATIONS = (
    "ADMISSIBLE_ENVIRONMENT_BINDING",
    "P0_EVENT_ORDER_BINDING",
    "NUMERIC_OBSERVATION_BINDING",
    "EXPLICIT_NOOP_AND_FIRST_VALID_BINDING",
    "FINITE_SAME_TIMESTAMP_CLOSURE",
    "POLICY_TIMING_KERNEL_STEP_CONFORMANCE",
    "TIMING_PROJECTION_PREFIX_REFINEMENT",
    "FIRST_HI_BAD_PREFIX_REFLECTION",
    "CONSTRAINED_DEADLINE_D_LE_T",
    "FIXED_PRIORITY_PREEMPTIVE_WORK_CONSERVING",
    "NO_SELF_SUSPENSION",
    "NO_UNMODELED_BLOCKING",
    "TOTAL_PRIORITY_OR_TIEBREAK_BINDING",
)
