"""Normative identifiers for the V9.2 proof route."""

PROOF_ROUTE = "POLICY_CONSTRAINED_EVENT_REFINED_SAFE_PREFIX_HI_SAFETY_V9_2"
REQUEST_SCHEMA = "proof_request_v9_2"
SCOPE = "P0_ZERO_CONTROLLER_OVERHEAD"
PRIMARY_CLAIM = "DEPLOYED_HI_SAFETY_P0"
RESULT_PROVED = "DEPLOYED_TREE_PROVED_P0"
RESULT_UNRESOLVED = "UNRESOLVED"
RESULT_INVALID = "PROOF_BUNDLE_INVALID"
RESULT_CONCRETE_COUNTEREXAMPLE = "CONCRETE_HI_COUNTEREXAMPLE_VERIFIED"

CANONICAL_PHASES = (
    "SETTLE_SERVICE_AND_REMOVAL",
    "IDLE_RECOVERY",
    "DEADLINE_OBSERVE",
    "ARRIVAL_BATCH_FREEZE",
    "MODE_SWITCH",
    "CONTROLLER",
    "FINAL_DISPATCH",
    "TIME_ADVANCE_AND_SERVICE",
)

KERNEL_STATE_FIELDS = (
    "t", "p", "m", "B", "eta", "J", "F", "M", "chi",
)

STATIC_OBLIGATIONS = (
    "ADMISSIBLE_ENVIRONMENT_BINDING",
    "P0_EVENT_ORDER_BINDING",
    "NUMERIC_OBSERVATION_BINDING",
    "EXPLICIT_NOOP_AND_FIRST_VALID_BINDING",
    "FINITE_SAME_TIMESTAMP_CLOSURE",
    "POLICY_TIMING_KERNEL_STEP_CONFORMANCE",
    "TIMING_PROJECTION_PREFIX_REFINEMENT",
    "FIRST_HI_BAD_PREFIX_REFLECTION",
    "SAFE_PREFIX_INVARIANT_INITIAL",
    "SAFE_PREFIX_INVARIANT_CONDITIONAL_INDUCTIVENESS",
    "EVENT_WINDOW_ENCODING_SOUNDNESS",
)
