from __future__ import annotations

ALL_TASK_REFERENCE_RTA_ARITHMETIC = "ALL_TASK_REFERENCE_RTA_ARITHMETIC"
REFERENCE_MODEL_CONFORMANCE = "REFERENCE_MODEL_CONFORMANCE"
REFERENCE_TASKSET_SCHEDULABLE = "REFERENCE_TASKSET_SCHEDULABLE"
REFERENCE_HI_SUBSET_SAFETY = "REFERENCE_HI_SUBSET_SAFETY"
BUDGET_ENVELOPE_TO_REFERENCE_DOMINATION = "BUDGET_ENVELOPE_TO_REFERENCE_DOMINATION"
EFFECTIVE_EVENT_FRONTIER_RELATION = "EFFECTIVE_EVENT_FRONTIER_RELATION"
CONTROLLER_WRITE_SET = "CONTROLLER_WRITE_SET"
CONTROLLER_BOUNDARY = "CONTROLLER_BOUNDARY"
CONTROLLER_PATH_UNIQUENESS = "CONTROLLER_PATH_UNIQUENESS"
TOKEN_REFRESH_PROJECTION = "TOKEN_REFRESH_PROJECTION"
UPDATE_PAYLOAD_TOTALITY = "UPDATE_PAYLOAD_TOTALITY"
CLOSED_PREFIX_REFINEMENT = "CLOSED_PREFIX_REFINEMENT"
REFERENCE_PREFIX_EXTENSION = "REFERENCE_PREFIX_EXTENSION"
HI_BAD_CLOSED_PREFIX_REFLECTION = "HI_BAD_CLOSED_PREFIX_REFLECTION"
EARLY_STOP_CLOSURE_COMPLETION = "EARLY_STOP_CLOSURE_COMPLETION"
EARLY_STOP_CONFIGURATION_GATE = "EARLY_STOP_CONFIGURATION_GATE"
FINITE_BAD_PREFIX_CONTRADICTION = "FINITE_BAD_PREFIX_CONTRADICTION"
FINAL_CLAIM_COMPOSITION = "FINAL_CLAIM_COMPOSITION"

LEGACY_PROTECTED_HI_IDS = frozenset({
    "PROTECTED_HI_RTA_ARITHMETIC",
    "PER_HI_TASK_INDUCTIVE_WCRT",
    "PROTECTED_HI_SAFETY_COROLLARY",
})
