"""工具链状态常量。"""

OBLIGATION_STATUSES = frozenset({"PASS", "FAIL", "UNRESOLVED", "NOT_APPLICABLE"})
CLAIM_STATUSES = frozenset({"DEPLOYED_TREE_PROVED",
    "PROOF_BUNDLE_INVALID", "MODEL_CONFORMANCE_FAILED",
    "CONCRETE_TIMING_COUNTEREXAMPLE", "POLICY_CONTRACT_VIOLATION",
    "REFERENCE_COUNTEREXAMPLE", "REFERENCE_CERTIFICATE_FAILED",
})
STATUSES = OBLIGATION_STATUSES | CLAIM_STATUSES
