"""target 提供给形式化核心的运行时 adapter protocol。"""

from __future__ import annotations

from typing import Any, Mapping, Protocol, Sequence


class FormalRuntimeAdapter(Protocol):
    """形式化核心只依赖此协议，不依赖 synthetic 或真实 runtime 实现。"""

    def extract_observation(self, runtime_state: Mapping[str, Any]) -> Sequence[float]: ...

    def quantization_input_state(self, runtime_state: Mapping[str, Any]) -> Mapping[str, Any]: ...

    def valid_action_mask(self, runtime_state: Mapping[str, Any]) -> tuple[Sequence[bool], Sequence[str]]: ...

    def apply_action(self, runtime_state: Mapping[str, Any], action_id: int | None) -> Mapping[str, Any]: ...

    def common_transition_witnesses(self) -> Sequence[Mapping[str, Any]]: ...

    def build_runtime_state_from_budget_vector(
        self, budget_by_task: Mapping[str, int]
    ) -> Mapping[str, Any]: ...

    def export_observation_contract(self) -> Mapping[str, Any]: ...

    def export_mask_contract(self) -> Mapping[str, Any]: ...

    def export_action_contract(self) -> Mapping[str, Any]: ...

    def export_source_binding_targets(self) -> Mapping[str, str]: ...

    def export_initial_state_contract(self) -> Mapping[str, Any]: ...

    def export_boot_transition_contract(self) -> Mapping[str, Any]: ...

    def export_budget_safety_polytope(self) -> Mapping[str, Any]: ...
