"""Complete prefix execution existence proofs.

Implements the four required execution-existence obligations:
  1. PROTECTED_PREFIX_CANONICAL_SUCCESSOR_TOTAL
  2. PROTECTED_PREFIX_SAME_TIME_CLOSURE_TERMINATES
  3. PROTECTED_PREFIX_TIME_DIVERGENCE
  4. PROTECTED_PREFIX_COMPLETE_EXECUTION_EXISTS

Each proof establishes a PARAMETERIZED property over all legal states,
not just one successful call to close_timestamp().
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, Mapping

from formal_toolchain.core.hashing import sha256_object
from dataclasses import replace

from formal_toolchain.bridge.logical_events import LogicalEventKind
from formal_toolchain.reference.executable_semantics import (
    initial_reference_state,
    is_closed_reference_state,
    next_logical_event,
    step_reference_p0,
)

from .input_oracle import ProtectedInputOracle, LazyInfiniteProtectedInputOracle
from .types import ProtectedPrefixBuildResult


# ---------------------------------------------------------------------------
# Section 7.2: Canonical closed-boundary successor
# ---------------------------------------------------------------------------


def _bind_oracle_for_current_arrival(state: Any, oracle: ProtectedInputOracle) -> Any:
    """Bind the authoritative projected input before processing an ARR_BATCH.

    The executable reference semantics reads release_demand_overrides and
    abnormal_hi_releases when opening the arrival batch.  This adapter updates
    those immutable maps from the single fixed protected oracle immediately
    before that batch is processed.
    """
    event = next_logical_event(state)
    if event is None or event.time != state.time or event.kind is not LogicalEventKind.ARR_BATCH:
        return state
    overrides = dict(state.release_demand_overrides)
    abnormal = set(state.abnormal_hi_releases)
    for task_name, release_index in event.batch_jobs:
        inp = oracle.input_for(task_name, release_index)
        if inp.job_key != (task_name, release_index) or inp.release_time != event.time:
            raise ValueError("PROTECTED_ORACLE_ARRIVAL_BINDING_MISMATCH")
        overrides[inp.job_key] = int(inp.actual_demand)
        if inp.hi_class == "ABNORMAL":
            abnormal.add(inp.job_key)
        else:
            abnormal.discard(inp.job_key)
    return replace(
        state,
        release_demand_overrides=overrides,
        abnormal_hi_releases=frozenset(abnormal),
    )


def next_closed_boundary(
    state: Any,
    taskset: object,
    oracle: ProtectedInputOracle,
) -> Any:
    """Execute to the next strictly later canonical closed boundary.

    This is an executable successor, not a totality proof.  It starts from a
    validated closed state, binds every encountered protected ARR_BATCH to the
    same fixed oracle, and repeatedly applies the code-faithful P0 step until a
    closed state at a strictly later time is reached.
    """
    if not is_closed_reference_state(state, taskset):
        raise ValueError("PROTECTED_PREFIX_SUCCESSOR_REQUIRES_CLOSED_STATE")
    start_time = int(state.time)
    current = state
    while True:
        current = _bind_oracle_for_current_arrival(current, oracle)
        current = step_reference_p0(current, taskset).after
        if int(current.time) > start_time and is_closed_reference_state(current, taskset):
            return current


# ---------------------------------------------------------------------------
# Section 7.3: Closure termination with lexicographic measure
# ---------------------------------------------------------------------------


_LEXICOGRAPHIC_MEASURE_ORDER = (
    "REM_t", "REC_t", "DDL_t", "ARR_t", "SW_t", "REL_t", "DSP_t",
)


def _closure_lexicographic_measure(
    state: Any,
) -> tuple[int, ...]:
    """Compute the lexicographic closure measure for a state.

    Section 7.3: the measure must strictly decrease at each closure micro-step
    and bottom out at zero in all components.

    The measure is restricted to the current timestamp.  Events generated by
    a handler are legal only in a later phase, so processing the current head
    strictly decreases the first changed component.
    """
    frontier = getattr(state, "frontier", ())
    from formal_toolchain.bridge.logical_events import LogicalEventKind
    current = [e for e in frontier if int(e.time) == int(state.time)]
    count = lambda kind: sum(1 for e in current if e.kind is kind)
    return (count(LogicalEventKind.REM), count(LogicalEventKind.REC),
            count(LogicalEventKind.DDL), count(LogicalEventKind.ARR_BATCH),
            count(LogicalEventKind.SW), count(LogicalEventKind.REL),
            count(LogicalEventKind.DSP))


def strict_lexicographic_decrease(
    pre: tuple[int, ...],
    post: tuple[int, ...],
) -> bool:
    """Check strict lexicographic decrease: pre > post.

    Returns True when there exists index i such that
    pre[0..i-1] == post[0..i-1] AND pre[i] > post[i].
    """
    for a, b in zip(pre, post):
        if a > b:
            return True
        if a < b:
            return False
    return False


def prove_closure_measure_well_founded() -> dict[str, Any]:
    """Prove: the lexicographic measure is well-founded (lower-bounded at zero).

    Each component is a non-negative integer count; the tuple is
    component-wise >= (0, 0, 0, 0, 0, 0).
    """
    return {
        "status": "PASS",
        "lemma": "CLOSURE_MEASURE_WELL_FOUNDED",
        "measure_order": list(_LEXICOGRAPHIC_MEASURE_ORDER),
        "lower_bound": tuple(0 for _ in _LEXICOGRAPHIC_MEASURE_ORDER),
        "argument": (
            "Every component is a non-negative integer count.  A finite "
            "lexicographic tuple of non-negative integers with component-wise "
            "lower bound (0,...,0) is well-founded by the standard "
            "lexicographic order on N^k."
        ),
    }


# ---------------------------------------------------------------------------
# Section 7.2 - 7.4: The four execution-existence proofs
# ---------------------------------------------------------------------------


def define_next_closed_boundary(
    prefix_taskset: object,
    protected_oracle: ProtectedInputOracle,
) -> dict[str, Any]:
    """Define the canonical closed-boundary successor function.

    The successor function is next_closed_boundary(), which applies the
    canonical macro-step (close_timestamp) to advance to the next closed
    boundary.
    """
    return {
        "schema_version": "canonical_successor_definition_v2",
        "function_name": "next_closed_boundary",
        "function_signature": (
            "next_closed_boundary(state: ReferenceState, "
            "taskset: ReferenceTaskset, oracle: ProtectedInputOracle) "
            "-> ReferenceState"
        ),
        "implementation": "next_closed_boundary(state, taskset, oracle)",
        "expected_properties": [
            "total over all legal closed states",
            "same-time closure measure strictly decreasing (lexicographic)",
            "post-closure: positive service tick OR jump to strictly future event",
            "time-divergent (no Zeno)",
        ],
        "closure_measure_well_founded": prove_closure_measure_well_founded(),
        "status": "UNRESOLVED",
        "code": "CANONICAL_SUCCESSOR_TOTALITY_PROOF_KERNEL_MISSING",
        "executable_successor_defined": True,
    }


def prove_canonical_successor_total(
    prefix_taskset: object,
    successor_definition: dict[str, Any],
    proof_kernel_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Prove: next_closed_boundary is a total function over legal closed states.

    The successor is close_timestamp(), which is total over all legal
    ReferenceState values by the C-AMC-sem semantics.  Every closed state
    has a well-defined next closed state because:
    1. The same-time closure has a strictly decreasing finite measure (Section 7.3).
    2. After closure, either a service tick advances time or a future event exists.
    """
    kernel_ok = (
        isinstance(proof_kernel_receipt, Mapping)
        and proof_kernel_receipt.get("status") == "PASS"
        and proof_kernel_receipt.get("theorem_id") == "PROTECTED_PREFIX_CANONICAL_SUCCESSOR_TOTAL"
        and proof_kernel_receipt.get("all_legal_closed_states_covered") is True
    )
    return {
        "obligation_id": "PROTECTED_PREFIX_CANONICAL_SUCCESSOR_TOTAL",
        "status": "PASS" if kernel_ok else "UNRESOLVED",
        "code": None if kernel_ok else "CANONICAL_SUCCESSOR_TOTALITY_UNRESOLVED",
        "successor_definition_hash": sha256_object(successor_definition),
        "reason": (
            "The successor is close_timestamp(), which is a pure function total "
            "over all legal closed states per C-AMC-sem semantics.  The closure "
            "measure is strictly decreasing and well-founded.  Post-closure either "
            "applies a service tick (+1 time) or jumps to a strictly future event."
        ),
    }


def prove_same_time_closure_terminates(
    successor_total_receipt: Mapping[str, Any] | None = None,
    proof_kernel_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Prove: same-time closure has a strictly decreasing finite measure.

    Uses the lexicographic count vector for the current timestamp in canonical
    phase order (REM, REC, DDL, ARR, SW, REL, DSP).

    Each micro-step processed by close_timestamp() removes one event from
    the frontier or advances a cursor, strictly decreasing the measure.
    The measure is well-founded, guaranteeing termination.
    """
    measure_ok = prove_closure_measure_well_founded()
    total_ok = (
        isinstance(successor_total_receipt, Mapping)
        and successor_total_receipt.get("status") == "PASS"
    )
    kernel_ok = (
        isinstance(proof_kernel_receipt, Mapping)
        and proof_kernel_receipt.get("status") == "PASS"
        and proof_kernel_receipt.get("theorem_id") == "PROTECTED_PREFIX_SAME_TIME_CLOSURE_TERMINATES"
        and proof_kernel_receipt.get("every_microstep_strictly_decreases_measure") is True
    )
    established = measure_ok["status"] == "PASS" and total_ok and kernel_ok

    return {
        "obligation_id": "PROTECTED_PREFIX_SAME_TIME_CLOSURE_TERMINATES",
        "status": "PASS" if established else "UNRESOLVED",
        "code": None if established else "SAME_TIME_CLOSURE_TERMINATION_UNRESOLVED",
        "closure_measure": list(_LEXICOGRAPHIC_MEASURE_ORDER),
        "measure_well_founded": measure_ok,
        "reason": (
            "Closure termination proof: (1) a well-founded lexicographic measure "
            "over the seven canonical same-time event phases; "
            "(2) every closure micro-step strictly decreases this measure; "
            "(3) the measure lower-bounds at (0,...,0)."
        ),
    }


def prove_time_divergence(
    closure_termination_receipt: Mapping[str, Any] | None = None,
    proof_kernel_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Prove: every canonical macro-step advances time, no Zeno.

    Post-closure, close_timestamp() either:
    - Executes SERVICE_UNIT: time += 1
    - Jumps to next future event: time := event_time > current_time

    Both cases strictly increase time.  By induction on macro-step count,
    time grows without bound (time-divergent).
    """
    closure_ok = (
        isinstance(closure_termination_receipt, Mapping)
        and closure_termination_receipt.get("status") == "PASS"
    )

    kernel_ok = (
        isinstance(proof_kernel_receipt, Mapping)
        and proof_kernel_receipt.get("status") == "PASS"
        and proof_kernel_receipt.get("theorem_id") == "PROTECTED_PREFIX_TIME_DIVERGENCE"
        and proof_kernel_receipt.get("every_macrostep_strictly_advances_time") is True
    )
    established = closure_ok and kernel_ok
    return {
        "obligation_id": "PROTECTED_PREFIX_TIME_DIVERGENCE",
        "status": "PASS" if established else "UNRESOLVED",
        "code": None if established else "TIME_DIVERGENCE_UNRESOLVED",
        "reason": (
            "Time divergence proof: post-closure macro-step either applies "
            "SERVICE_UNIT (time+1) or jumps to next event time > current. "
            "Both cases strictly increase time.  By induction on macro-step "
            "count, time grows without bound."
        ),
    }


def prove_complete_execution_exists(
    *,
    time_divergence_receipt: Mapping[str, Any] | None = None,
    input_projection_receipt: Mapping[str, Any] | None = None,
    prefix_taskset: object,
    protected_oracle: ProtectedInputOracle | None = None,
    prefix_initial_state: Any = None,
    single_witness_receipt: Mapping[str, Any] | None = None,
    proof_kernel_receipt: Mapping[str, Any] | None = None,
    idle_jump_expansion_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Prove: a unique time-divergent execution exists for the projected oracle.

    Section 7.5: The proof binds one fixed oracle to one complete prefix
    execution.  The witness must certify:
        same_fixed_oracle = true
        same_initial_state = true
        same_successor_function = true
        all_finite_prefixes_are_prefixes_of_one_execution = true
    """
    try:
        _ = initial_reference_state(prefix_taskset)
        initial_ok = True
    except (TypeError, ValueError, RuntimeError):
        initial_ok = False

    div_ok = (
        isinstance(time_divergence_receipt, Mapping)
        and time_divergence_receipt.get("status") == "PASS"
    )
    proj_ok = (
        isinstance(input_projection_receipt, Mapping)
        and input_projection_receipt.get("status") == "PASS"
    )

    witness_ok = (
        isinstance(single_witness_receipt, Mapping)
        and single_witness_receipt.get("status") == "PASS"
        and single_witness_receipt.get("quantifier_order")
            == "forall-full-exists-one-prefix-forall-boundaries"
        and single_witness_receipt.get("same_fixed_oracle") is True
        and single_witness_receipt.get("same_initial_state") is True
        and single_witness_receipt.get("same_successor_function") is True
        and single_witness_receipt.get("all_finite_prefixes_are_prefixes_of_one_execution") is True
        and single_witness_receipt.get("single_complete_execution") is True
    )
    kernel_ok = (
        isinstance(proof_kernel_receipt, Mapping)
        and proof_kernel_receipt.get("status") == "PASS"
        and proof_kernel_receipt.get("theorem_id") == "PROTECTED_PREFIX_COMPLETE_EXECUTION_EXISTS"
        and proof_kernel_receipt.get("dependent_choice_construction_verified") is True
        and proof_kernel_receipt.get("recurring_history_preserved") is True
        and proof_kernel_receipt.get("same_fixed_oracle") is True
    )
    idle_expansion_ok = (
        isinstance(idle_jump_expansion_receipt, Mapping)
        and idle_jump_expansion_receipt.get("status") == "PASS"
        and idle_jump_expansion_receipt.get("theorem_id")
            == "PROTECTED_PREFIX_IDLE_JUMP_STUTTER_EXPANSION"
        and idle_jump_expansion_receipt.get("all_integer_times_observable") is True
        and idle_jump_expansion_receipt.get("protected_observable_stutters_on_expanded_idle_ticks") is True
    )
    projected_oracle_fingerprint = (
        input_projection_receipt.get("witness", input_projection_receipt).get("projected_oracle_fingerprint")
        if isinstance(input_projection_receipt, Mapping) else None
    )
    single_oracle_fingerprint = (
        single_witness_receipt.get("projected_oracle_fingerprint")
        if isinstance(single_witness_receipt, Mapping) else None
    )
    oracle_binding_ok = (
        isinstance(projected_oracle_fingerprint, str)
        and isinstance(single_oracle_fingerprint, str)
        and projected_oracle_fingerprint == single_oracle_fingerprint
    )
    established = (
        initial_ok and div_ok and proj_ok and witness_ok and kernel_ok
        and idle_expansion_ok and oracle_binding_ok
    )

    return {
        "status": "PASS" if established else "UNRESOLVED",
        "code": None if established else "COMPLETE_EXECUTION_EXISTS_UNRESOLVED",
        "obligation_id": "PROTECTED_PREFIX_COMPLETE_EXECUTION_EXISTS",
        "witness": {
            "schema_version": "complete_execution_existence_v3",
            "initial_state_constructible": initial_ok,
            "time_divergent": div_ok,
            "projected_oracle_defined": proj_ok,
            "single_complete_execution": established,
            "single_witness_receipt_verified": witness_ok,
            "same_fixed_oracle": witness_ok,
            "same_initial_state": True if witness_ok else False,
            "same_successor_function": "next_closed_boundary" if initial_ok else None,
            "all_finite_prefixes_are_prefixes_of_one_execution": witness_ok,
            "recurring_history_preserved": established,
            "idle_jump_expansion_verified": idle_expansion_ok,
            "time_indexed_closed_observation_defined": idle_expansion_ok,
            "projected_oracle_fingerprint": projected_oracle_fingerprint,
            "single_witness_oracle_fingerprint": single_oracle_fingerprint,
            "same_projected_oracle": oracle_binding_ok,
        },
        "failure": None if established else {
            "code": "COMPLETE_EXECUTION_EXISTS_UNRESOLVED",
            "reason": (
                "Complete execution existence requires: time divergence "
                "proof PASS, input projection receipt PASS, initial state "
                "constructible, and a proof-kernel receipt binding one fixed "
                "oracle to one complete prefix execution with the quantifier "
                "order 'forall-full-exists-one-prefix-forall-boundaries', and "
                "an idle-jump stutter expansion defining Close(t) at every integer time."
            ),
        },
    }


def build_complete_prefix_execution_witness(
    *,
    prefix_initial_state: Any,
    prefix_taskset: Any,
    protected_oracle: ProtectedInputOracle,
    transition_totality_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """Legacy wrapper, delegates to prove_complete_execution_exists."""
    successor_def = define_next_closed_boundary(prefix_taskset, protected_oracle)
    total = prove_canonical_successor_total(prefix_taskset, successor_def)
    closure = prove_same_time_closure_terminates(total)
    divergence = prove_time_divergence(closure)

    return prove_complete_execution_exists(
        time_divergence_receipt=divergence,
        input_projection_receipt={"status": "UNRESOLVED", "code": "PROJECTED_ORACLE_THEOREM_RECEIPT_REQUIRED"},
        prefix_taskset=prefix_taskset,
        protected_oracle=protected_oracle,
        prefix_initial_state=prefix_initial_state,
        single_witness_receipt=None,
        proof_kernel_receipt=None,
    )
