"""Proof-side checks for idle-jump protected-observable stuttering."""

from __future__ import annotations

from typing import Any, Sequence

from formal_toolchain.core.hashing import sha256_object
from .time_indexed_close import close_at, verify_time_indexed_domain


def prove_idle_jump_stutter_expansion(
    *,
    execution: Sequence[Any] | None,
    observable_projector: Any = None,
) -> dict[str, Any]:
    """Verify inserted ticks preserve the projected protected state.

    The execution is an input generated by the fresh verifier.  No synthetic
    trace or finite demand witness is created here.
    """
    if execution is None:
        return {"status": "UNRESOLVED", "code": "IDLE_EXPANSION_EXECUTION_MISSING"}
    domain = verify_time_indexed_domain(execution, observable_projector=observable_projector)
    if domain.get("status") != "PASS":
        return domain
    inserted = []
    times = [int(state.time) for state in execution]
    for left, right in zip(execution, execution[1:]):
        if int(right.time) <= int(left.time) + 1:
            continue
        baseline = close_at(execution, int(left.time), observable_projector=observable_projector).protected_observable
        for t in range(int(left.time) + 1, int(right.time)):
            obs = close_at(execution, t, observable_projector=observable_projector)
            if obs.protected_observable != baseline:
                return {"status": "FAIL", "code": "IDLE_EXPANSION_PROTECTED_OBSERVABLE_CHANGED"}
            inserted.append(t)
    payload = {
        "theorem_id": "PROTECTED_PREFIX_IDLE_JUMP_STUTTER_EXPANSION",
        "status": "PASS",
        "all_integer_times_observable": domain["all_integer_times_observable"],
        "time_indexed_closed_observation_defined": True,
        "protected_observable_stutters_on_expanded_idle_ticks": True,
        "inserted_idle_ticks": inserted,
        "execution_time_fingerprint": domain["execution_time_fingerprint"],
    }
    payload["receipt_hash"] = sha256_object(payload)
    return payload
