from __future__ import annotations

import json
from pathlib import Path

from formal_toolchain.core.registry import load_registry
from formal_toolchain.verifier.aggregator import claim_dependency_closure


def build_snapshot(project_root: Path) -> dict:
    registry = load_registry(
        project_root / "formal_toolchain/specs/obligation_registry.json"
    )
    active = [row for row in registry if row["activation"] == "active"]
    required = [row for row in active if row["required"] is True]
    zero_predecessor_required = sorted(
        row["id"] for row in required if not row["depends_on"]
    )
    closure = claim_dependency_closure(registry, "DEPLOYED_HI_SAFETY")
    return {
        "schema_version": "global_audit_snapshot_v2",
        "registry_entry_count": len(registry),
        "active_count": len(active),
        "required_count": len(required),
        "claim_closure": sorted(closure),
        "zero_predecessor_required": zero_predecessor_required,
        "notes": [
            "This snapshot is generated by scripts/generate_global_audit_snapshot.py",
            "Tests must check structural invariants, not hardcoded counts",
        ],
    }


def main() -> None:
    root = Path(__file__).resolve().parents[1]
    out = root / "build/formal/global_audit_current.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(
        json.dumps(build_snapshot(root), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )


if __name__ == "__main__":
    main()
